### ISSUE TITLE
Virtual stick to control actual drone

### ISSUE THREAD

**Issue by VMWH** [dji-sdk/Mobile-SDK-Android#1006]
I would like to use the virtual joystick to control the real DJI Phantom 4 but in the DJI Sample Code which can found here "https://github.com/dji-sdk/Mobile-SDK-Android". The virtual joystick just able to use in simulation but couldn't work with the actual DJI drone.

Is there any ideas how can I link the virtual joystick to the actual DJI drone?

Thanks

Sorry for the broken English.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51982'>Zendesk ticket #51982</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51982'>Zendesk ticket #51982</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
The sample also can work in a real flight, but please do not enable the simulator feature.

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
