### ISSUE TITLE
M300 flight limited to 400m when using DJI mobile SDK

### ISSUE THREAD

**Issue by idani301** [dji-sdk/Mobile-SDK-Android#1009]
M300 with latest firmware and with latest DJI mobile sdk version. 
When using sendVirtualStickFlightControlData , drone stop to "listen" to sendVirtualStickFlightControlData function when it is more far than 400m from home. 
getVirtualStickModeEnabled still returns "true" but we cannot control the drone. 
We still see video and we still can control the gimbal/camera, or even control the drone by using "sport" mode. 

we tried 3 different areas and 2 different drones, the bug happens in every single one of them so it will be easy to reproduce.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/52080'>Zendesk ticket #52080</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/52080'>Zendesk ticket #52080</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
We have handle it in your Zendesk ticket, please follow up.

Thanks,

Luce Luo
DJI Developer Support
<br><p><em><small>°°°</small></em></p>
