### ISSUE TITLE
WaypointV2MissionOperatorView源码疑问

### ISSUE THREAD

**Issue by aforme** [dji-sdk/Mobile-SDK-Android#1010]
示例代码中，[WaypointV2MissionOperatorView的第824行](https://github.com/dji-sdk/Mobile-SDK-Android/blob/6b50e89e71420c089d11c3888d887e0024078c87/Sample%20Code/app/src/main/java/com/dji/sdk/sample/demo/missionoperator/WaypointV2MissionOperatorView.java#L824) 这里为什么是associateActionId+5（1+5=6），actionid6对应的是waypointAction6Actuator的拍照

源码部分：
        // Periodically capture photos
        WaypointTrigger waypointAction14Trigger = new WaypointTrigger.Builder()
                .setTriggerType(ActionTypes.ActionTriggerType.ASSOCIATE)
                .setAssociateParam(new WaypointV2AssociateTriggerParam.Builder()
                        .setAssociateActionID(**associateActionId+5**)
                        .setAssociateType(ActionTypes.AssociatedTimingType.AFTER_FINISHED)
                        // Because set file name and shoot photo is the same module, it is better to set a waiting time.
                        .setWaitingTime(0.5f)
                        .build())
                .build();

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/52088'>Zendesk ticket #52088</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from sean.zhou in <a href='https://djisdksupport.zendesk.com/agent/tickets/52088'>Zendesk ticket #52088</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

这个只是设置触发器的触发时机，在执行完 waypointAction6Actuator的拍照动作后触发这个触发器，看代码中在执行完 waypointAction6Actuator 的拍照动作后，还关联了一个重置云台的动作。waypointAction14Trigger  这里的关联应该有问题，应该是想要关联 waypointAction13 的动作，而不是 associateActionId+5。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
