### ISSUE TITLE
Mavic 2 zoom WaypointMissionOperator.startMission后，状态仍为ready_to_execute

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#1021]

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/52937'>Zendesk ticket #52937</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from sean.zhou in <a href='https://djisdksupport.zendesk.com/agent/tickets/52937'>Zendesk ticket #52937</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

那说明调用 startMission 时出现了错误，麻烦提供一下 startMission 的回调错误码和错误信息描述。

如果还有什么问题，欢迎继续联系我们。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Swordce** [comment]
startMission回调是成功的。。。所以才会有这个问题

**Comment by dji-dev** [comment]
Agent comment from sean.zhou in <a href='https://djisdksupport.zendesk.com/agent/tickets/52937'>Zendesk ticket #52937</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

startMission 回调成功了，但是状态仍为 ready_to_execute，此时飞机是否开始执行任务了？麻烦详细描述一下整体过程。

如果还有什么问题，欢迎继续联系我们。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by Swordce** [comment]
startMission成功后，无人机按照航线正常飞行，然后在飞行过程中执行pauseMission。执行pauseMission前会调用operator.getcurrentState返回的值就是ready_to_execute

**Comment by dji-dev** [comment]
Agent comment from sean.zhou in <a href='https://djisdksupport.zendesk.com/agent/tickets/52937'>Zendesk ticket #52937</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

我们按照您的描述进行测试，并没有复现您的问题。如果状态为 ready_to_execute，此时调用 pauseMission 并不会成功，会报“The execution could not be executed.”的错误啊。麻烦提供一下您的固件版本以及 MSDK 的版本，以及您调用 getcurrentState 前后的代码片段。

如果还有什么问题，欢迎继续联系我们。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
