### ISSUE TITLE
推流的时候总是出现这个Error

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#1023]
![QQ图片20210909165825](https://user-images.githubusercontent.com/16829238/132656085-c35959b5-b703-45a1-ab0e-442446d1a1e7.png)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/53018'>Zendesk ticket #53018</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
图传底层崩溃了，是什么机型呢？

**Comment by Swordce** [comment]
![image](https://user-images.githubusercontent.com/16829238/132836819-27fba6ee-f8fb-4f92-a5d3-bccfbe9911c4.png)
![image](https://user-images.githubusercontent.com/16829238/132836872-205c5848-69c3-44bb-a5bf-7bf55119887c.png)
这是相关的代码片段，这个bug出现非常频繁，请问应该如果解决或者避免

**Comment by Swordce** [comment]
@DJI-William

**Comment by DJI-William** [comment]
把AudioStream那个设置取消掉试试，另外Sample运行会有崩溃吗？

**Comment by Swordce** [comment]
sample没有测试这么多，这个集成在App里的也不是必现，出现的的莫名其妙。你说的这个我取消掉再测试测试


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月10日(周五) 晚上7:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dji-sdk/Mobile-SDK-Android] 推流的时候总是出现这个Error (#1023)




 
把AudioStream那个设置取消掉试试，另外Sample运行会有崩溃吗？
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Swordce** [comment]
不行啊，还是不停重复调用start和stop，然后就会报这个error

**Comment by Swordce** [comment]
@DJI-William 能不能给个解决方案呀~

**Comment by Michael-DJI** [comment]
> 不行啊，还是不停重复调用start和stop，然后就会报这个error，有办法捕获这个error么 @DJI-William

为什么要不断重复调用start和stop呢？

**Comment by Swordce** [comment]
> > 不行啊，还是不停重复调用start和stop，然后就会报这个error，有办法捕获这个error么 @DJI-William
> 
> 为什么要不断重复调用start和stop呢？

因为在推流过程中，由于网络等原因推流会中断，就需要调用stop后重新调用start开启推流

**Comment by DJI-William** [comment]
崩溃得是底层，我们需要测试一下。LiveSteamManager设计得不是很好，MSDK 5.0版本会进行重构。如果实在解决不了你可以尝试自己开发推流直播模块。

**Comment by Swordce** [comment]
> 崩溃得是底层，我们需要测试一下。LiveSteamManager设计得不是很好，MSDK 5.0版本会进行重构。如果实在解决不了你可以尝试自己开发推流直播模块。

@DJI-William 5.0有计划大概什么时候发布吗

**Comment by DJI-William** [comment]
预计明年过年后。
