### ISSUE TITLE
Wind speed and direction that is present in DJI Pilot.

### ISSUE THREAD

**Issue by IuliuNovac** [dji-sdk/Mobile-SDK-Android#1027]
Hi,

Right now in the DJI Pilot for the m300 you can see the wind speed and direction. I would like to know how or when it would be possible to obtain this value from MSDK. Here is the section of the m300 documentation that shows the feature. 

![New Bitmap Image (19)](https://user-images.githubusercontent.com/22908508/134488992-e8579c44-a568-4eb9-94ad-1137634241e4.jpg)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/53697'>Zendesk ticket #53697</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
For M300, there is no interface for WIND_DIRECTION or WIND_SPEED, we only provide keys to access those values, please use keyManager to access them.
Link：https://developer.dji.com/api-reference/android-api/Components/KeyManager/DJIFlightControllerKey.html?search=wind&i=0&#flightcontrollerkey_wind_speed_key
Link：https://developer.dji.com/api-reference/android-api/Components/KeyManager/DJIFlightControllerKey.html?search=wind&i=1&#flightcontrollerkey_wind_direction_key
