### ISSUE TITLE
Will Mobile-sdk provide depth image of Phantom4's look-forward stereo camera?

### ISSUE THREAD

**Issue by KahnShi** [dji-sdk/Mobile-SDK-Android#103]
Hi all,

I have a suggestion that will mobile-sdk provide access to the depth map of Phantom4's look-forward stereo camera, just like what they do in guidance-sdk?
The reason is that we could use this data to conduct good dynamic obstacle avoidance research.

FYI
Best,
Kahn

**Comment by dji-dev** [comment]
Hi @KahnShi , thanks for your suggestions, currently, we don't support this feature in mobile-sdk. We will investigate this feature and inform developers if we have supported it in the future SDK release.

**Comment by talobin** [comment]
Hi @KahnShi . 
It is not available on Mobile SDK since SDK doesn't have access to this type of data.
However, the OnboardSDK will have this feature in the coming released if you are interested.
Although, it will not support P4. If you really need to access this data, I would suggest to use M210 aircraft instead.
Thanks
