### ISSUE TITLE
直播推流过程中，有时画面会突然模糊然后再变清晰，这种情况有办法优化么

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#1062]

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/56343'>Zendesk ticket #56343</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by Swordce** [comment]
getLiveVideoBitRateMode获取到是MANUAL，在网络不好的情况下也会降低视频分辨率保证视频的流畅性么？

**Comment by Swordce** [comment]
@dji-dev @DJI-William

**Comment by DJI-William** [comment]
降低分辨率，提高直播码率。

**Comment by Swordce** [comment]
setLiveVideoBitRate的范围是什么，sdk里面能调用，但是文档没有

setTranscodingDataRate需要设置么，是不是值越高越好
@DJI-William

**Comment by Swordce** [comment]
M300搭载H20T的时候，设置setTranscodingDataRate并没有提高直播码率

**Comment by DJI-William** [comment]
setLiveVideoBitRate忘记把接口开放了，实际上是可以使用的，setTranscodingDataRate是图传码率。setLiveVideoBitRate是直播码率，提高一下试试。

**Comment by Swordce** [comment]
直播码率有设置范围吗，大概设置成多少会合适

**Comment by DJI-William** [comment]
没给设置范围，setTranscodingDataRate是0.3-20的范围，我想setLiveVideoBitRate不可能超过他，你试试5，10，15，20都试试。
