### ISSUE TITLE
Mavic 2 pro availableCaptureCount

### ISSUE THREAD

**Issue by santa010** [dji-sdk/Mobile-SDK-Android#1067]
Did anyone encounter an issue on Mavic 2 Pro (didn't seem to happen on Phantom 4 Pro) when using StorageState.Callback? 
When checking for `availableCaptureCount` I get 2 responses, the first value is normal and then followed by another response with `availableCaptureCount` being `0`.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/56861'>Zendesk ticket #56861</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
one response is internal storage and the other one is SD card. It seems like you havn't insert a SD card.

**Comment by santa010** [comment]
Ah interesting. The SD card was inserted in the drone, but it could be, that the internal storage is full. Is there a way to differentiate internal storage response from the SD card one?

**Comment by DJI-William** [comment]
From these 2 response, you can call isInserted to know if this callback if from internal storage or SD card.

**Comment by santa010** [comment]
Thank you, that did the trick!
