### ISSUE TITLE
provideTranscodedVideoFeed和primaryVideoFeed的数据流格式分别是什么类型的，能否直接用来进行rtmp推流

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#1076]

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/57992'>Zendesk ticket #57992</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
primaryVideoFeed输出的是DJI格式的H.264，SPS和PPS信息都回被去掉。provideTranscodedVideoFeed是标准格式的H.264，你可以用这个推流。

**Comment by Swordce** [comment]
我用ffmpeg对provideTranscodedVideoFeed的数据进行推流，结果一直失败
请问provideTranscodedVideoFeed回调中的byte[]数组要如何转成ffmpeg需要的uint_8类型的数据
![image](https://user-images.githubusercontent.com/16829238/146498633-0487a90e-7e47-4ea9-ade7-559bf734e418.png)
![image](https://user-images.githubusercontent.com/16829238/146498653-790913f5-dcb9-4433-ab09-5d725f48a552.png)

**Comment by Swordce** [comment]
@DJI-William

**Comment by Swordce** [comment]
provideTranscodedVideoFeed中获取到的视频尺寸是1088*720的，这个视频尺寸是不是错的？使用的机型是御2行业版

**Comment by DJI-William** [comment]
具体怎么做需要你自己研究，我记得时把H.264用FFMPEG打包成FLV推送的。应该不会有错，我们的LiveStreamManager就是从也是从这些接口拿的流。

**Comment by kubbo** [comment]
> 具体怎么做需要你自己研究，我记得时把H.264用FFMPEG打包成FLV推送的。应该不会有错，我们的LiveStreamManager就是从也是从这些接口拿的流。


请问  【provideTranscodedVideoFeed】这个方法获取到的 h264 流为什么只是 720P 的，如果获取 1080p 的 H264 ?

**Comment by DJI-William** [comment]
> > 具体怎么做需要你自己研究，我记得时把H.264用FFMPEG打包成FLV推送的。应该不会有错，我们的LiveStreamManager就是从也是从这些接口拿的流。
> 
> 请问 【provideTranscodedVideoFeed】这个方法获取到的 h264 流为什么只是 720P 的，如果获取 1080p 的 H264 ?

打开这个开关再试试setHDLiveViewEnabled。
