### ISSUE TITLE
Photo, sensors, GPS location time stamp 

### ISSUE THREAD

**Issue by saimouli** [dji-sdk/Mobile-SDK-Android#1078]
I would like to sync sensor measurements when the photo is taken at a waypoint using the timestamps. In the Mobile API I did not find how to retrieve time stamps from the measurements.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/58356'>Zendesk ticket #58356</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
All the measurements are automatically saved in images' EXIF/metadata. You can download the photos to your phone and use any 3rd party lib to extract those information out. There is no MSDK API to read them.

**Comment by saimouli** [comment]
I would like to get the information in real time. For example at waypoint Lat: 30, Long: 20, I need the timestamp of the photo taken, and attitude information of the camera at that instant

**Comment by DJI-William** [comment]
From the setNewGeneratedMediaFileInfoCallback, everytime when there is a new media file is generated, this callback will be called. And you can call getTimeCreated. At that time, you can use flightController.setStateCallback's callback to call getAircraftLocation to get the location of the aircraft.
