### ISSUE TITLE
Not working with the Air2S / RC Pro combo

### ISSUE THREAD

**Issue by flythecode** [dji-sdk/Mobile-SDK-Android#1079]
Not working with the Air2S / RC Pro combo. Old Smart Controller works but not with the RC pro combo.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/58565'>Zendesk ticket #58565</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
It does support Smart Controller RM500, please update your SDK to 4.16.

**Comment by flythecode** [comment]
4.16 does not support the RC pro with the mavic air 2s.

**Comment by flythecode** [comment]
It does not detect the aircraft

**Comment by flythecode** [comment]
The conventional old SC does detect it but the new bundle that comes with
the RC pro did not detect the aircraft.

**Comment by DJI-William** [comment]
Yes, Air2S current does not support new the bundle RC Pro, we will support in 4.16.1 version.
