### ISSUE TITLE
p4r无人机拍摄照片。取回SD卡后，通过Java file api 获取最后修改时间，获取到的时间戳比当前时间晚了9小时。

### ISSUE THREAD

**Issue by SJJ-dot** [dji-sdk/Mobile-SDK-Android#1080]
![aa](https://user-images.githubusercontent.com/15243969/147729918-8af7c52c-9bbc-431a-8c92-46b5f523f4eb.png)

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/58570'>Zendesk ticket #58570</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
最后修改时间是移动设备同步过去的，看看是不是设备时间有问题。

**Comment by SJJ-dot** [comment]
不是
