### ISSUE TITLE
Sample app does not recognize Mavic 2 Zoom

### ISSUE THREAD

**Issue by gg-deploy-dd** [dji-sdk/Mobile-SDK-Android#1090]
The sample app is stuck on the main page stating product is not recognized when connected to Mavic 2 Zoom. 
Equipment:
Drone - Mavic 2 Zoom with regular controller
Mobile device - 
1.           a. Samsung S21 running Android 12
2.           b. Samsung Tab A7 running Android 11

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59050'>Zendesk ticket #59050</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
We have tested S21 before releasing and its fine. Have you changed any settings inside the Sample? Please be note that the Android SDK version inside build.gradle must be equal or less than 30. But it can still running on Android SDK version 31 device.

**Comment by gg-deploy-dd** [comment]
No changes in the sample app besides adding the app key in the manifest. The same drone can be recognized by our DroneDeploy app using the 4.16 dji sdk though. But the sample app refuses to detect the drone

**Comment by DJI-William** [comment]
If the app cannot recognise this aircraft, it will say Unknown Aircraft. Would you please record a video for me to show what the issue looks like?
Link：https://pan-sec.djicorp.com/s/GDMcP8kfed38oLJ
dji123

**Comment by gg-deploy-dd** [comment]
Hello William, I have uploaded the video of the issue. Thanks for taking a look.

**Comment by DJI-William** [comment]
I didn't see you click the register app button. When you click the register app, a message of registeration should pop up.

**Comment by gg-deploy-dd** [comment]
Hello William, clicking on register app button results in 'The metadata received from server is invalid, please reconnect to the server and try.(255)' error.

**Comment by DJI-William** [comment]
The problem most lilly is the app key. Please have a look the AndroidManifest.xml file and your appkey. Since you are using our sample app, you app key's bundle idenfier must mathes with our project name which is com.dji.sdk.sample.

**Comment by gg-deploy-dd** [comment]
Hello William, any amount of trying I did to register the app with my app id did not work. As an alternative I used our company's app id and after refactoring the app to the new namespace was able to register the sample app. However id does not recognize the drone after that. I have attached the video. Could you take a look?

**Comment by DJI-William** [comment]
I have uploaded a video for testing M2P on my side which shows there is no problem on my side. Would you switch to another Type-C cable or smart phone? Maybe this will help.

**Comment by gg-deploy-dd** [comment]
Hello William. Figured out the issue. 

1. I was not using the app id when we create the app. It was stuck in the default app id
2. The application permissions list never gets empty when I hit the register app even if all the permissions are approved for the app. I had to move the call to register app outside of the permissions gate in the main activity.

Thanks for looking into this issue :)
