### ISSUE TITLE
Air2S Gimbal Attitude

### ISSUE THREAD

**Issue by flythecode** [dji-sdk/Mobile-SDK-Android#1095]
Due to firmware problem, MSDK can not get he gimbal attitude data in this
version. It will be supported in later version. Is this going to be fixed on 4.16.1?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59431'>Zendesk ticket #59431</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
This issue cannot be fixed in 4.16.1 version, it can only be fixed in the next firmware version. So it is out of our hands.
