### ISSUE TITLE
调用直播时候在等距离航拍,直播会有延迟或者停顿

### ISSUE THREAD

**Issue by ShikinChen** [dji-sdk/Mobile-SDK-Android#1096]
如题

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59460'>Zendesk ticket #59460</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
直播的时候拍照会有一定延迟和卡顿是正常的，因为拍照并且生成照片的时候视频流会被掐断。你会发现哪怕不是直播的时候，你拍照也会造成视频流一定卡顿。
