### ISSUE TITLE
lockTakeoffWithoutGPS is missing from DJI MSDK 4.15 FlightController

### ISSUE THREAD

**Issue by KhairulM** [dji-sdk/Mobile-SDK-Android#1099]
DJI SDK: 4.15

Hi DJI team,

I just wanted to ask, according to the [documentation](https://developer.dji.com/api-reference/android-api/Components/FlightController/DJIFlightController.html#djiflightcontroller_locktakeoffwithoutgps_inline ) if I need to take off in a GPS-denied / low GPS environment I need to unlock takeoff without GPS, but when I checked the FlightController class, there is no method named `lockTakeoffWithoutGPS()`, so is there any way that I can take off in such condition without calling the lock takeoff method?

Thank you.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59736'>Zendesk ticket #59736</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/59736'>Zendesk ticket #59736</a>:<br><br>I have confirmed with the engineer, you could use startTakeoff directly, the weak gps signal could not be restricted.
<br><p><em><small>°°°</small></em></p>

**Comment by KhairulM** [comment]
Okay thank you!
