### ISSUE TITLE
Sample app crashes on Mavic 2 Enterprise when starting live stream

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1101]
The following line is causing the sample app to crash when connected to the Mavic 2 Enterprise:

`int result = DJISDKManager.getInstance().getLiveStreamManager().startStream();`

Crash: 

```
E/DJIUSBWifiSwitchManager: ****resetSwitchFromWifiFlag
E/DJIUsbAccessoryReceiver: receiver destroySession
    Receiver not registered: dji.midware.usb.P3.DJIUsbAccessoryReceiver@7612941
E/AndroidRuntime: FATAL EXCEPTION: Thread-399
    Process: com.dji.sdk.sample, PID: 5926
    java.lang.NullPointerException: Attempt to invoke virtual method 'dji.midware.media.opengl.fdd$fdd dji.midware.media.opengl.fdd.dgh(java.lang.String)' on a null object reference
        at dji.midware.media.opengl.ddf.nhf.fdd(Unknown Source)
        at dji.midware.media.DJIVideoDecoder.setSecondaryOutputInterval(Unknown Source)
        at dji.midware.media.transcode.fullframe.FullFrameHardwareTranscoder.gfd(Unknown Source)
        at dji.sdk.sdkmanager.LiveStreamManager.fetchSpsPps(Unknown Source)
        at dji.sdk.sdkmanager.LiveStreamManager.startStream(Unknown Source)
        at com.dji.sdk.sample.demo.camera.LiveStreamView$3.run(:198)
```

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59902'>Zendesk ticket #59902</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
Known issue, change the View from SurfaceView to TextureView will solve this issue, or wait until 4.16.1 version.
