### ISSUE TITLE
Mini 2 - Live video feed does not work on Pixel 6 Phones

### ISSUE THREAD

**Issue by JohnalHub** [dji-sdk/Mobile-SDK-Android#1102]
The non-functioning live video feed for Pixel 6 devices (running Android 12) was an issue with an older version of the DJI Fly app that was eventually resolved. The issue still exists within the currently released SDK.  

I'm hoping that the fix used for the DJI Fly app can be implemented in the next SDK release for Android.

Full disclosure: I emailed DJI and heard back that it was a known issue that would likely be resolved in the next SDK Release (end of February), but since I didn't see it posted here as a known issue I thought I'd submit it.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59921'>Zendesk ticket #59921</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
Either Email or github issue will work, you only need to submit once, we are fixing this issue in this sprint.
