### ISSUE TITLE
WebRTC live streaming?

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1103]
Are there any plans to support WebRTC live streaming through the LiveStreamManager? It's significantly less latent than the RTMP implementation currently.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/59922'>Zendesk ticket #59922</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
We are about to release MSDK 5.0 soon and the live streaming module will be refactored. We will release a demo of how to live streaming in GB28281, webRTC and RTMP protocols.

**Comment by saimouli** [comment]
@DJI-William approximately when will MSDK 5.0 be released? this month?

**Comment by DJI-William** [comment]
The first beta version will be release on March, we will give a full Demo when it comes out. You can get GPS data but you cannot get sensor data each frame.
