### ISSUE TITLE
The command is not supported by the current firmware version

### ISSUE THREAD

**Issue by sonth-bhsoft** [dji-sdk/Mobile-SDK-Android#1108]
Hi,
I got this error message "The command is not supported by the current firmware version" while trying to set the camera mode to **SettingsDefinitions.CameraMode.MEDIA_DOWNLOAD**
Does anyone know how to fix it?
I work with the SDK 4.15.1, the Mavic Air 2 and firmware version 01.01.07.11 (the newest).

Thanks.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/60223'>Zendesk ticket #60223</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
Don't use setMode to enter download mode, use camera.enterPlayback to enter the download mode.

**Comment by sonth-bhsoft** [comment]
Oh, thank you.

**Comment by dji-dev** [comment]
Agent comment from cheney.zeng in <a href='https://djisdksupport.zendesk.com/agent/tickets/60223'>Zendesk ticket #60223</a>:<br><br>You are welcome, hope you have nice day.
<br><p><em><small>°°°</small></em></p>
