### ISSUE TITLE
Read SDK logs offline

### ISSUE THREAD

**Issue by gab933** [dji-sdk/Mobile-SDK-Android#1114]
Hi,
how can I read sdk .log files not at run-time, but offline/post-processing?
Many topics suggest logcat, but I'm not able to read post-processing logs, only run-time with it.
Thank you,

Gabriele

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/61174'>Zendesk ticket #61174</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
You cannot, it can be only analysis by our company's confidential script. It is used to debug.
