### ISSUE TITLE
RTMPS Support

### ISSUE THREAD

**Issue by ggpaeg** [dji-sdk/Mobile-SDK-Android#1115]
Hi, 

I'm using Android LiveStreamManager. It seems not to support RTMPS live stream, only RTMP is supported. 
Is there a way to use RTMPS on LiveStreamManager? If there is not, It could be implemented soon? 
Every big streaming service is requiring RTMPS encoders nowadays.

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/61186'>Zendesk ticket #61186</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
We are not going to implement RTMPS protocol live stream in the future. It is better you develop by yourself.
