### ISSUE TITLE
4.16.1 Drone takeoff error

### ISSUE THREAD

**Issue by gg-deploy-dd** [dji-sdk/Mobile-SDK-Android#1127]
With the latest sdk I am getting the following error

> Plan upload failed: OK

It seems to be a regression since it worked with 4.16. Any thoughts/suggestions on when it would be fixed or if there is a workaround for this issue?

Thanks

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/62002'>Zendesk ticket #62002</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
Which API cause this error and how to reproduce it?

**Comment by gg-deploy-dd** [comment]
Hello @DJI-William ,

The following function 

> MissionControlManager -> getWaypointMissionOperator().loadMission(...)
returns the following DJIError object with description
> The execution could not be executed.

**Comment by DJI-William** [comment]
Have you look at your current state? if you current state is not "NOT_READY", "RECOVERING"，“READY_TO_UPLOAD”, "READY_TO RETRY_UPLOAD" and READY_TO_EXECUTE, then this error will return.

**Comment by gg-deploy-dd** [comment]
Hello William,
Yes, we do check for the state before we try to upload the mission
`state == WaypointMissionState.READY_TO_UPLOAD`
One interesting point is that none of our code has changed. The app with 4.16 sdk works however with 4.16.1 does not.
Did some code around the waypoint/mission change in 4.16.1?
Thanks

**Comment by DJI-William** [comment]
No, I have checed the source code. Only the above condistions are satisfied and then this error will return. Perhaps can you shoot a video record for me to demostrate this error please?
https://pan-sec.djicorp.com/s/JR4qtwKbccWFjGJ
dji123

**Comment by gg-deploy-dd** [comment]
Hello @DJI-William 
It looks like it was an error on my end. Sorry for the issue and taking your time.
Thanks
