### ISSUE TITLE
M300 H20T provideTranscodedVideoFeed  如何获取1080p 分辨率视频？

### ISSUE THREAD

**Issue by kubbo** [dji-sdk/Mobile-SDK-Android#1128]
我们通过  provideTranscodedVideoFeed 获取到H264分辨率只有 720P ，请问通过 provideTranscodedVideoFeed 如何获取到1080p的H264 流？

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/62499'>Zendesk ticket #62499</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
把高清画质打开试试，看看这篇文章：
Link：https://sdk-forum.dji.net/hc/zh-cn/articles/900006809383

**Comment by kubbo** [comment]
M300 并不支持此方法的。

**Comment by DJI-William** [comment]
这个问题我询问了一下研发，虽然setVideoResolutionAndFrameRate改变了图传的分辨率，但是编码器依然会把图传缩小到原来的分辨率。所以我们需要改变编码器的设置，你试试setLiveVideoResolution这个函数，虽然它是直播库里的，但是这个函数会改变编码器的设置，你不开直播就可以了，试试看。

**Comment by kubbo** [comment]
收到。

**Comment by DJI-William** [comment]
@kubbo 这样做是否有效果？
