### ISSUE TITLE
Forced update to MSDK 5.0?

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1143]
The new firmware update broke my app, which uses MSDK 4.16.

Is MSDK 4.16 now obsolete? Do I need to completely migrate to MSDK 5.0?

**Comment by kenargo** [comment]
I’m using 4.16.1 and the firmware works just fine  Out of curiosity, what broke?

 

Since 5.0 is still in beta,  I doubt that it would be suggested for production use until it’s released.

 

From: Bevin Benson ***@***.***> 
Sent: Tuesday, May 17, 2022 3:42 PM
To: dji-sdk/Mobile-SDK-Android ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dji-sdk/Mobile-SDK-Android] Forced update to MSDK 5.0? (Issue #1143)

 

There was a forced firmware update, as well as a mandated update to DJI Pilot 2, on the M300 that I noticed today. This broke my app, which uses MSDK 4.16.

Is MSDK 4.16 now obsolete? Do I need to completely migrate to MSDK 5.0?

**Comment by bbenson09** [comment]
It looks like a problem with the registration process. 

@kenargo is your M300 running v04.00.01.11, released 5/11/22?

**Comment by kenargo** [comment]
Yes, same firmware, works perfectly, I didn’t need to change my source code at all.  Worked with out of the box.

 

I assume you mean SDK registration? I doubt that code would even have changed between versions, or it would break all existing apps.

**Comment by DJI-William** [comment]
I strongly suggest you use 4.16.1 since 4.16 has lots of crash reports. But none of them came from registration process.

**Comment by bbenson09** [comment]
Problem was on my end... sorry for the confusion. Thanks.
