### ISSUE TITLE
Apps Fail to build for apps targeting Android 12

### ISSUE THREAD

**Issue by andrewdittmer** [dji-sdk/Mobile-SDK-Android#1145]
Apps containing DJI SDK fail to build with a target SDK version is set to 31 or higher, 

`Error: android:exported needs to be explicitly specified for element <service#com.mapzen.android.lost.internal.GeofencingIntentService>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported`

**Comment by andrewdittmer** [comment]
Due to manifest merge failure related to the GeofencingIntentService from the com.mapzen.android library.

**Comment by DJI-William** [comment]
Are you using our latest version 4.16.1? If yes, the issue seems like you need to add android:exported in your AndroidManifest.xml. Please have a look our Sample demo, it has been updated and targeted to 31.
![image](https://user-images.githubusercontent.com/77274755/169442753-719b651c-2f26-412d-96c0-d21b271a84cc.png)

**Comment by andrewdittmer** [comment]
Updating to 4.16.1 solved this problem. Thanks
