### ISSUE TITLE
calculateTotalTime / calculateTotalDistance for WaypointV2Mission?

### ISSUE THREAD

**Issue by bbenson09** [dji-sdk/Mobile-SDK-Android#1200]
Hi, do methods similar to `calculateTotalTime` and `calculateTotalDistance` exist for WaypointV2Missions, or are these only offered in the normal WaypointMission Builder?

I would like to calculate the mission time for missions on the M300 drone as shown in DJI Pilot.

Thanks.

**Comment by DJI-William** [comment]
These only offer to the normal WaypointMission Builder. We cancel these 2 properties because they are so inaccurate so they are useless. If you really want them, you can just use trigonometric to calculate the distance between 2 co-ordinates and calculate the time according to its point speed or waypoint overall speed. The result is so rough because the aircraft never flies in a constant speed and you can only estimate the time cost for actions.

**Comment by bbenson09** [comment]
That makes sense, thank you
