### ISSUE TITLE
[Help] ActiveTrackOperator.startTracking()

### ISSUE THREAD

**Issue by huongta157** [dji-sdk/Mobile-SDK-Android#1289]
<img width="794" alt="Screenshot 2024-04-11 at 14 50 00" src="https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/becd5015-2d55-45ec-b222-cf28cb6c7888">

<img width="596" alt="Screenshot 2024-04-11 at 14 51 37" src="https://github.com/dji-sdk/Mobile-SDK-Android/assets/46671455/3b40af61-451d-4d2e-a665-933e24e83349">

- I got the error message when using this code: Unknown object target do not support tracking
- Device model: DJI Air 2s

Please help me check it.

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104810'>Zendesk ticket #104810</a>:<br><br>The reason why the mission cannot be initiated is that the aircraft cannot recognize the target selected. If the aircraft does not enter the AIRCRAFT_FOLLOWING state after you input the selected target, you will need to adjust the box-selected target so that the aircraft can recognize it correctly.

The air 2s supports automatic target recognition function, you can also try using it.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
> automatic target recognition function

@dji-dev Any document for this function?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104810'>Zendesk ticket #104810</a>:<br><br>Currently, we do not have specific documentation explaining it because it is just a part of the intelligent tracking feature. `enableAutoSensing` is the switch to enable target recognition. In the listener of `ActiveTrackOperator`, you can obtain `TrackingState`, where you can get the targets recognized by the aircraft and their positions on the screen.
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev Thank you for answer, but it still does not work, any other ideas?

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104810'>Zendesk ticket #104810</a>:<br><br>Based on the error message you provided, the aircraft did not recognize the target you outlined. You will need to re-outline the target you want the aircraft to follow and try initiating the follow mode again. Generally, people, cars, and boats are good targets for follow mode.

The mention of the automatic recognition feature is because once the automatic recognition feature is enabled, the aircraft will show the targets it has recognized, preventing situations where the aircraft fails to recognize a target. However, these recognized targets may not be the ones you are looking for.

Here is a sample code for your reference:https://github.com/DJI-Mobile-SDK-Tutorials/Android-Phantom4Missions
<br><p><em><small>°°°</small></em></p>

**Comment by huongta157** [comment]
@dji-dev thank you so much

**Comment by dji-dev** [comment]
Agent comment from yating.liao in <a href='https://djisdksupport.zendesk.com/agent/tickets/104810'>Zendesk ticket #104810</a>:<br><br>I am glad to help you.
<br><p><em><small>°°°</small></em></p>
