### ISSUE TITLE
4.3 DJI SDK issue - list of supported devices has shortened 

### ISSUE THREAD

**Issue by Anna-Pogribnyak** [dji-sdk/Mobile-SDK-Android#165]
Recently we updated DJI SDK in our app from 3.4 to 4.3 and list of supported Android devices in Google Play Console immediately shortened. Any ideas what caused this?

Version with SDK v 3.4
<img width="1083" alt="sdk3 4" src="https://user-images.githubusercontent.com/9572273/30820005-524fac70-a229-11e7-8958-1f077942db78.png">
Version with SDK v 4.3
<img width="1011" alt="sdk4 3" src="https://user-images.githubusercontent.com/9572273/30820004-52366af8-a229-11e7-8d8b-27b43ed2f0e3.png">

Screenshots attached

**Comment by JamesMasterman** [comment]
Hi Anna-Pogribnyak,  I noticed this too. It's because DJI have mysteriously added a required feature to the SDK manifest (android.hardware.telephony). This excludes any device that is Wifi only. The list is effectively reduced to phones, or tablets with LTE.

You can fix this by adding this line to your AndroidManifest.xml, just below the uses-permission section.

 <uses-feature android:name="android.hardware.telephony" android:required="false" />

I haven't noticed any ill effects by doing this, I regularly using a Wifi only tablet for testing (Samsung S2). 

The Play store uses the "uses-feature" directive in the manifest to limit the devices that is shows as compatible with your app.

**Comment by talobin** [comment]
@Anna-Pogribnyak My guess would be the difference in permissions required like @JamesMasterman suggested.
