### ISSUE TITLE
Correct Manifest.xml for v4.4.1 going forward

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Mobile-SDK-Android#216]
Could we get a quick check on the correct contents for the manifest.xml file going forward? The sample app uses one version and while the 'Integrate SDK into Application instructions for android' uses a different format found here: https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html

I'm assuming that the sample code contains the correct version but I wanted to check. 

Specifically is it still necessary to define an activity as the DJIAoaControllerActivity as well as a service as a DJIGlobalService found in this code: 

<activity
    android:name="dji.sdk.sdkmanager.DJIAoaControllerActivity"
    android:theme="@android:style/Theme.Translucent" >
    <intent-filter>
        <action android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED" />
    </intent-filter>
    <meta-data
        android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED"
        android:resource="@xml/accessory_filter" />
</activity>
<service android:name="dji.sdk.sdkmanager.DJIGlobalService" >
</service>

Thanks,

**Comment by oliverou** [comment]
Hi @Djacob502, since they are different Android Studio projects, it's normal to have different content in the AndroidManifest.xml file.

To upgrade your current project to Android SDK 4.4.1, you can follow the [Integrate SDK into Application](https://developer.dji.com/mobile-sdk/documentation/application-development-workflow/workflow-integrate.html) tutorial for reference, this tutorial assumes you start to create your Android Studio project from scratch. 

If you already have an application class in your project, please check the [Creating a Camera Application](https://developer.dji.com/mobile-sdk/documentation/android-tutorials/index.html) tutorial to learn how to upgrade it.

We also provide a FAQ to help developers upgrade their projects to Android SDK 4.4.1: <https://developer.dji.com/mobile-sdk/documentation/faq/index.html#after-upgrading-to-dji-android-sdk-4-4-1-my-android-project-crashes-with-java-lang-noclassdeffounderror-error-how-to-fix-it>

Hope these help!

**Comment by Djacob502** [comment]
Thanks for the feedback and knowing there are two methods to handle the integration.

**Comment by Michael-DJI** [comment]
Hi, did you resolve your issue?
if not, pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
