### ISSUE TITLE
Feature Request: DJI Widgets Imperial Units

### ISSUE THREAD

**Issue by Stevenhua03** [dji-sdk/Mobile-SDK-Android#299]
I noticed that the Dashboard widget containing the Distance Home, Horizontal Velocity, Distance RC, Vertical Velocity and Altitude widgets all use Metric units, could you guys add a version using Imperial units?

We have a number of users who use imperial units instead and would like to be able to support their preferences. Its a small change that would save a us a lot of time making our own replacement widgets  and I'm sure other end users would like it as well.

**Comment by kenargo** [comment]
You can implement the imperial display yourself, you need to override the individual controls and override the appropriate methods for display.

 

Yes, I agree it should be a property of the control but at least for now there is an easy solution.

**Comment by kenargo** [comment]
As of 4.6, you can create a class that extends the widgets and use code similar to the following:

        if (Application.getGlobalSettings().userPreferences.isMetricMode() == true) {
            setWidgetUnitType(dji.ux.c.i.a.a);
        } else {
            setWidgetUnitType(dji.ux.c.i.a.b);
        }

Note: the DJI class should implement the functionality as supported part of the class but at leas in the short term there is a solution.

Note2: for 4.5.x SDK the enums where dji.ux.d.i.a.a anddji.ux.d.i.a.b (so yo may need to update the code for each DJI release as the enum class may change due to proguard of the SDK.

**Comment by Stevenhua03** [comment]
Fair enough

**Comment by Michael-DJI** [comment]
pls report the issue to dev@dji.com it's the official channel to request DJI SDK support now.
