### ISSUE TITLE
Does DJI support Android 9 yet?

### ISSUE THREAD

**Issue by Daxito** [dji-sdk/Mobile-SDK-Android#370]
I am having issues upgrading my App to Android Pie/9 and before I spend days trying to figure out workarounds etc I would like to know if DJI already supports this version of Android.
Thanks!

**Comment by matthewdlloydlp** [comment]
I'm also having issues anytime I update the target/compilesdkversion to 28.

**Comment by kenargo** [comment]
If you are using the UI library then I don't believe it's possible as DJI uses appcompat 27 internally. 

I don't know about mobile SDK specifically. 

⁣Sent from BlueMail ​

**Comment by matthewdlloydlp** [comment]
@kenargo Do you know if they plan on updating that soon?

**Comment by kenargo** [comment]
Given that they just released 4.8.1 a short time ago,  I wouldn't bet on a release soon. 

I hope i'm wrong. 

I'm waiting on critical fixes and real map widget support.   Have been waiting since some functionality was regressed in 4.7 and remains unfixed to this day. 

I remain hopeful though

⁣Sent from BlueMail ​

**Comment by Daxito** [comment]
I am using UI Library, I hope DJI guys can confirm this and let us know when this upgrade might be available, I have a bunch of new users that have the Pixel 3 Phones with Android 9 already....

**Comment by Daxito** [comment]
Never mind, I got rid of the DJI SDK, I will find other options.
