### ISSUE TITLE
LiveStreamManager is delayed a lot

### ISSUE THREAD

**Issue by tubipham** [dji-sdk/Mobile-SDK-Android#400]
I use the LiveStreamManager, it's work but there are about 10 seconds latency
@Michael-DJI Is there any way to fix it?

Device Phantom3 pro
DJI SDK: 4.9
UX SDK: 4.9

**Comment by Qiaoxinghua** [comment]
我的是Manifest.permission.RECORD_AUDIO权限没有申请，加上就好了，看看对你有没有帮助

**Comment by PanGuangwei** [comment]
> 我的是Manifest.permission.RECORD_AUDIO权限没有申请，加上就好了，看看对你有没有帮助

666,有效果

**Comment by Michael-DJI** [comment]
@tubipham could this issue be closed?

**Comment by chrisail** [comment]
Hi.
Using Github sample application on Android SDK 4.11.1 with a DJI Mavic Air, the latency is always between 10 and 15 seconds .

It's not due to the Youtube RTMP server which works like a charm when using webcam.

Sample application already define "Manifest.permission.RECORD_AUDIO".
Activating/deactivating sound or reencoding doesn't improve latency.

LiveStream informations are:
 - Video Bitrate between 1700-2700 kpbs
 - Audio around 680 kpbs
 - Video FPS around 30
 - Vide cache size between 1 and 2 frames

Is this latency a feature or a dysfunction ?

Thank you
