### ISSUE TITLE
Multiple apps using the mobile sdk

### ISSUE THREAD

**Issue by alexsullivan114** [dji-sdk/Mobile-SDK-Android#433]
Is it possible to run multiple apps utilizing the mobile SDK at the same time? Like let's say I wanted to build an app that streamed telemetry or some other information from the drone to some server, but I also wanted to be able to use the DJI Go app while I was streaming that information. Would that be possible, or can only one app utilize the SDK at a given time?

**Comment by kenargo** [comment]
Sorry but the SDK only supports a single app connection at a time.

⁣Get BlueMail for Android ​

**Comment by alexsullivan114** [comment]
Got it. I'll close this issue, but would you know perhaps if the Dji GO app exposes some mechanism for streaming telemetry that would negate the need to write a new app that uses the mobile SDK?

**Comment by neilyoung** [comment]
You could create an app based on the SDK, which mocks the DJI Go app for the flight and transfers telemetry (as far as you can obtain in via the SDK) via WebRTC data channel to remote

**Comment by kenargo** [comment]
I don't think the GO app exposes anything,  but even if it did,  DJI doesn't document it. 

For security reasons,  I'm being it doesn't. 

You can build a new flight app but of course that's excessive to rebuild an app that mimics the GO app unless your requirements are minimal and you could live with a minimal app otherwise it would be quite an undertaking. 

⁣Get BlueMail for Android ​

**Comment by Michael-DJI** [comment]
> Got it. I'll close this issue, but would you know perhaps if the Dji GO app exposes some mechanism for streaming telemetry that would negate the need to write a new app that uses the mobile SDK?

GO only support streaming the live video to a rtmp server
