### ISSUE TITLE
Will timeline mission recover after power off?

### ISSUE THREAD

**Issue by ohaujingjing** [dji-sdk/Mobile-SDK-Android#495]
If the mission will take vary long time and has to change battery in the middle of the mission, will the aircraft continue operating the mission after power on again, will the mission storage in the memory?

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32994'>Zendesk ticket #32994</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
No, the drone will not continue to the mission because the drone will be reset after power on again.

So, you need to store the rest of the waypoints first and upload them again after the power on again.

Thanks,

Luce Luo
DJI Dev Team

**Comment by kenargo** [comment]
There is (kind-of) something that will help (getPreviousInterruption) but unfortunately it’s only for the Phantom 4 RTK.  For all other aircrafts you are on your own.

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/32994'>Zendesk ticket #32994</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Yes, sorry it's supported by the P4RTK for the being time.

Thanks,

Luce Luo
DJI Dev Team
