### ISSUE TITLE
YUV callback delivers totally random crop size for each drone

### ISSUE THREAD

**Issue by keivanh** [dji-sdk/Mobile-SDK-Android#499]
I am testing with 4.11.1 and 4.11.2, we have several Mavic 2 pro drones, all drones and remote controllers are identical regards the firmware version. Android device and the app version is also same on all tests, problem is on each combination of Drone/RC/Android device we get different video output from onYuvDataReceived. 

Here is part of the code initializing video callback:

`codecManager = new DJICodecManager(mContext, null, DJIYVUWidth, DJIYVUHeight, UsbAccessoryService.VideoStreamSource.Camera);
        codecManager.enabledYuvData(true);
        codecManager.setYuvDataCallback(frameListener);` 

DJIYVUWidth and DJIYVUHeight is hard coded to 1280 and 720 but they are totally ignored by SDK, regardless of what I set for width and height, SDK returns whatever it likes!

Variations we have:
1- Android 9 -> color-space 19, 1280x720, ratio 16:9
2- Android 9 -> color-space 19, 1088x720, ratio 3:2
3- Android 10 -> color-space 21, 1280x720, ratio 16:9

But problem is not limited to this, on one of the drones (combination 1) we get "cropped" image, it is like camera is zooming around 20%. 

I am trying to run image processing over the frames and these random variations makes it impossible to have unique approach for all Mavic 2 Pro drones.

Ratio change has been solved by setting  
`camera.setPhotoAspectRatio(SettingsDefinitions.PhotoAspectRatio.RATIO_16_9, ...)`

before starting CodecManager, but all other attempts to set video size or resetting the "crop" view failed. Is there any way to force SDK to deliver unique video configuration for all "Mavic 2 pro"s on same android device?

Following #422 it seems SDK selects a configuration based on underling Android capabilities, but in our case, Android device (software and hardware and actual device) is exactly same in each test and only drones are changing.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33072'>Zendesk ticket #33072</a>:<br><br>Dear Client
Thank you for contacting DJI.

Hi, we have passed this issue to the developing team. However, due to the busy situation of our develop team, they may not respond to this very soon. We promise that we will go back to you once we get feedback from devs.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by keivanh** [comment]
Also new one: 1920x1088, FPS 29.97 NTSC, Color space 19 (What is that 8 pixel??!!!?)

**Comment by keivanh** [comment]
New findings:
Images from problematic drone (cropped images) looks completely flat while for over drones are distorted. It means for that drone anti distortion is enable. I excluded anti distortion library form the app, so I guess drone itself is applying the anti distortion.

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/33072'>Zendesk ticket #33072</a>:<br><br>Dear Client
Thank you for contacting DJI.

Our dev team has scheduled this issue to be solved in 4.12.2 patch. Thanks for your report.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support

**Comment by jeryini** [comment]
Hello @dji-dev!

Was this issue solved? I can't find it in release logs.

Cheers,
Jernej

**Comment by Jim-DJI** [comment]
@keivanh @jeryini  Hi, in order to ensure the best presentation for each camera, the sdk directly spit out the code stream according to the original code stream resolution, and each aircraft will encode the appropriate resolution code stream according to the sensor capabilities. In order to meet your needs, you can receive the code stream in 'onYuvDataReceived' and do corp processing. Can it can solve your problem?

**Comment by Jim-DJI** [comment]
> anti
At present, some prototype aircrafts cannot support anti-distortion. It is recommended to include anti-distortion library.

**Comment by jeryini** [comment]
Hello @Jim-DJI ! I didn't have problems like that any more, as I'm using DJI UX SDK library to subscribe to raw video byte stream.

**Comment by Jim-DJI** [comment]
@keivanh Do you need any help? If not, I will close the issue
