### ISSUE TITLE
Change the emissivity of the IR camera

### ISSUE THREAD

**Issue by manuoso** [dji-sdk/Mobile-SDK-Android#531]
Hi,

I am measuring objects with the thermal camera on the Mavic 2 Enterprise Dual, and I would like to know if it is possible to change the emissivity value to 0.98 in order to measure the temperature of human people.

I have found this function setThermalSceneEmissivity but it doesn't work, the temperature is the same after applying that command as without it.

If not possible, is there a way, using software, to compensate the temperature it measures to calibrate itself against a human temperature? I dont want to use the app DJI Pilot with calibrate temperature, I try to understand what is done to change that temperature to the calibrated temperature.

Best,
Manuel.

**Comment by dji-dev** [comment]
Dear Manuel,

Thank you for contacting DJI.
It's impossible to use Mavic 2 Enterprise Dual measure human body temperature instead of the thermometer!
Because 
In general, under the model of High Gain/ Low Gaini case,  measurement temperature will exist 5% -10% error range.
And Human body heat standard 37.2 ℃, if use Mavic 2 Enterprise Dual to measure, measurement temperature minimum existence 1-2 ℃ difference (low in truth).
Also, the MSDK doesn't support this method setThermalSceneEmissivity and have no way to calibrate it.
So, please do not use Mavic 2 Enterprise Dual to measure human body temperature, please use a standard thermometer.
​
![image](https://user-images.githubusercontent.com/11869194/83253167-1a586100-a1df-11ea-8035-1c71eec99551.png)

Body temperature measurement and temperature measurement using the guide for building guidance.

**Comment by manuoso** [comment]
Thank you very much for your reply.
My intention was not to use it to measure the temperature of the human body. I was just looking for how viable it was, and as you have answered me well, the IR sensor of the Mavic 2 Enterprise Dual does not serve this purpose.

Thank you so much for everything.

Best regards,
Manuel.
