### ISSUE TITLE
Limited networking when uav connects

### ISSUE THREAD

**Issue by annesteenbeek** [dji-sdk/Mobile-SDK-Android#532]
I am building an app where i have a companion program running on my laptop on the same WiFi network. 
I am sending images from the android phone to the desktop app using web Sockets.
However, I am running into the problem, where when the UAV (mavic in this case) connects to the remote, networking  on the android device is reduced to near 0. I am still able to send small packets, however, uploading images is impossible.

I've also tested with other apps, all networking on my phone is blocked until the drone disconnects again. 
If only the remote is connected this is no problem.
Is this expected behavior? Or could the remote be congesting android sockets?
I am using the DJI SDK 4.11 with android 9.

Any help or information would be appreciated.

**Comment by dji-dev** [comment]
Dear Client
Thank you for contacting DJI.

Hi, which drone model are you using? If you are using Mavic Air and this model supports WiFi connection. Maybe its the WiFi connection block your Android device network. Otherwise if you are using mobile->Remote controller->drone connection, your internet connection shouldn't be lost.

**Comment by annesteenbeek** [comment]
I am using the Mavic Pro, however, i've been able to narrow the problem down. It most likely has to do with the mavic interferring with the WiFi channel. When I switch to 4g, or create a hotspot on my phone, and connect the laptop to that network, full network performance is restored.
