### ISSUE TITLE
Mavic mini does not support MissionAction's GoToAction action.

### ISSUE THREAD

**Issue by qimikimi** [dji-sdk/Mobile-SDK-Android#606]
The following code can run in Mavic 2, and it will get stuck in "GoToAction "when running in Mavic mini.

elements.add(new TakeOffAction());
elements.add(new GoToAction(new LocationCoordinate2D(homeLatitude, homeLongitude), 10));
elements.add(new GoHomeAction());

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/38816'>Zendesk ticket #38816</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
Sorry, it's not an MSDK problem, because the Mavic Mini doesn't support any of the missions including the GoToAction, limited by the firmware.

Thanks,

Luce Luo
DJI Developer Support

**Comment by ryaa** [comment]
What are the models that fully support all missions?
