### ISSUE TITLE
SDK Registration Failed

### ISSUE THREAD

**Issue by Aditya239233** [dji-sdk/Mobile-SDK-Android#700]
When I start the sample app, I first get a notification saying: Registering, pls wait... but then later, my SDK registration fails. And the message I get is: SDK registration failed. Please check the bundle ID and network connectivity. I'm facing this issue on an Android Device. 
Does the SDK registration succeed only when a DJI drone is connected via USB?

**Comment by kenargo** [comment]
Registration of the SDK does not require connection to the aircraft, it only requires connection to the internet.

 

Have you created and registered the app in the DJI Developer <https://developer.dji.com/>  account?  Activated the registration (you should get an email after creating the app)?  Copied the appID into the manifest file (see example below)?

 

<application
    android:name=".MyApplication"
…
    <meta-data
        android:name="com.dji.sdk.API_KEY"
        android:value="PLACE IT HERE!!!" />

**Comment by Aditya239233** [comment]
Yes, I did. My bundle identifier is com.dji.sdk.APP_KEY and i did fill in my  app key in AndroidManifest.xml

**Comment by kenargo** [comment]
That sounds like the wrong identifier (is com.dji.sdk.APP_KEY ).  It should match the package name from the top of the file:

 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package=" com.dji.sdk"

 

Or whatever you have in that space

**Comment by Aditya239233** [comment]
yup, that indeed did the trick. Thankss!

**Comment by mastermisteri55** [comment]
I also happened to have the same problem before (about 2 hour ago)... and already try all methods that have been discussed here and in some other posts, but in the end, my problem is actually in bundle.gradle(:app) where the 'applicationId' in 'defaultConfig' block is not change to my app package name yet because I simply copy&paste 100% of the sample gradle without check it first... tbh, this is my 1st time try DJI-sdk..

sorry for my bad english...
