### ISSUE TITLE
DJI SDK Waypoint Mission - UploadMission error

### ISSUE THREAD

**Issue by laboBea** [dji-sdk/Mobile-SDK-Android#863]
I'm developing an Android Application that uses the DJI SDK. The drone I'm using right now is the Mavic Pro 1. This application wants to use the predefined classes for waypoints inside the DJI SDK to create missions for the drone, but when performing the configuration of the Waypoint mission and correctly loading the mission inisde the Mission Operator (current state is set to: READY_TO_UPLOAD after calling the MissionOperator.loadMission), when trying to perform the "uploadMission" predefined function the app crashes and the Drone automatically disconects of the Application.

I think the waypoints are correctly created and saved inside the builder, otherwise it would fail in the loadMission function. Also the parameters are correct since the checkParameters function is used.

I have seen that some people in previous posts say that you need first to set the application to Ground station mode. But I don't find any indications of this existing inside the DJI SDK documentation, so I think it is deprecated and not needed anymore for current versions of the SDK, if you could confirm this would be of great help.

Is the Upload of the mission inside the Operator failing because I am using a Mavic Pro 1 maybe?

If anyone has the correct steps to setup Waypoint missions or knows the error it would be of great help for all the DJI SDK users.

Best regards, Thanks in advance

**Comment by kenargo** [comment]
Lacking code and crash stack it is difficult to determine the cause of the crash but as for "ground station" mode,  there is no such thing. If you would be so kind as to paste in a crash stack it might be easier to assist.   The crash stack will point to where in the code the crash is detected so it's very helpful. 
-------- Original message --------From: laboBea ***@***.***> Date: 5/3/21  6:19 AM  (GMT-08:00) To: dji-sdk/Mobile-SDK-Android ***@***.***> Cc: Subscribed ***@***.***> Subject: [dji-sdk/Mobile-SDK-Android] DJI SDK Waypoint Mission - UploadMission error (#863) 
I'm developing an Android Application that uses the DJI SDK. The drone I'm using right now is the Mavic Pro 1. This application wants to use the predefined classes for waypoints inside the DJI SDK to create missions for the drone, but when performing the configuration of the Waypoint mission and correctly loading the mission inisde the Mission Operator (current state is set to: READY_TO_UPLOAD after calling the MissionOperator.loadMission), when trying to perform the "uploadMission" predefined function the app crashes and the Drone automatically disconects of the Application.
I think the waypoints are correctly created and saved inside the builder, otherwise it would fail in the loadMission function. Also the parameters are correct since the checkParameters function is used.
I have seen that some people in previous posts say that you need first to set the application to Ground station mode. But I don't find any indications of this existing inside the DJI SDK documentation, so I think it is deprecated and not needed anymore for current versions of the SDK, if you could confirm this would be of great help.
Is the Upload of the mission inside the Operator failing because I am using a Mavic Pro 1 maybe?
If anyone has the correct steps to setup Waypoint missions or knows the error it would be of great help for all the DJI SDK users.
Best regards, Thanks in advance

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/47240'>Zendesk ticket #47240</a>:<br><br>Dear Client
Thank you for contacting DJI.

The Mavic Pro supports WaypointMission and we are sure that the Sample Project can run waypintMission. Is it possible to show any crash error message?

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support<br><p><em><small>°°°</small></em></p>

**Comment by laboBea** [comment]
Thank you for contacting me, I can't really provide of a crash report since by the time the crash is produced I am using the drone physically, far from the debugger mode. If it is 100% mandatory I could try to find a way to get it, but I know exactly which is the function that is failing. It is the following function:

private void uploadWayPointMission(){

    getWaypointMissionOperator().uploadMission(new CommonCallbacks.CompletionCallback() {
        @Override
        public void onResult(DJIError error) {
            if (error == null) {
                setResultToToast("Mission upload successfully!");
            } else {
                setResultToToast("Mission upload failed, error: " + error.getDescription() + " retrying...");
                getWaypointMissionOperator().retryUploadMission(null);
            }
        }
    });

}`

It is in concret the line: `getWaypointMissionOperator().uploadMission(new CommonCallbacks.CompletionCallback() {` that is causing the crash.

The state of the Mission Operator is checked before calling this function and it is "READY_TO_UPLOAD" so I don't know where can be failing.

Tried to surround it with try/catch but it does not work anyway, the view of the map in which I am designing the mission close and the Mavic pro is automatically disconnected from the android device I'm using to control it and I need to reset the app to regain the connection with the drone.

Could it be because of FlySafe? I am doing the mission inside an "Authorization Zone" (blue color in DJI GEO Zone), my drone has the athorization to fly there and if I want, I can fly it manually without problems, also the state of the drone is "Ready to fly" so it shouldn't be a problem but maybe the Waypoint mission don't allow it?

To create the mission I create two waypoints by clicking in the map (as before two you are not allowed to loadMission) and everything is fine until the upload of the mission inside the Mission Operator.

Thank you again,

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/47240'>Zendesk ticket #47240</a>:<br><br>Dear Client
Thank you for contacting DJI.

I feel like you shoun't call retryupload in else. Anyway, could you try the sample demo and see if you can run it correctly.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support<br><p><em><small>°°°</small></em></p>

**Comment by laboBea** [comment]
Hello,

The issue was solved and the Waypoint mission works normally.
The problem (in case someone is in the same situation) was that when uploading the misson it tried to plot a Toast at screen that crashed the application. The problem was not the uploadMission itself.
Solved by simply inputing:
                    runOnUiThread {
                    }
And the Toasts inside the brackets. Now it works fine.

Just one last question, what is the objective of downloadMission function of the missionOperator?

Best regards,

**Comment by yali25** [comment]
> Hello,
> 
> The issue was solved and the Waypoint mission works normally.
> The problem (in case someone is in the same situation) was that when uploading the misson it tried to plot a Toast at screen that crashed the application. The problem was not the uploadMission itself.
> Solved by simply inputing:
> runOnUiThread {
> }
> And the Toasts inside the brackets. Now it works fine.
> 
> Just one last question, what is the objective of downloadMission function of the missionOperator?
> 
> Best regards,

Thank you for your explanation. 
I have similar problem. Can you show the source code of the upload mission function together with runOnUiThread{ }
Thank you.

**Comment by laboBea** [comment]
The problem is not the uploadMission itself, but the onUploadUpdate listener, that in my case was trying to call a Toast inside it, my upload function is the same I wrote at the begining, it is not modified and it works fine. 
The application was being killed because it was trying to plot a Toast in screen that was not allowed. If you put all the toasts as lambdas inside runOnUiThread{ } it is going to work fine if you have the same problem I was having.
