### ISSUE TITLE
Return to home Problem

### ISSUE THREAD

**Issue by laboBea** [dji-sdk/Mobile-SDK-Android#917]
Hello,

When performing waypoint missions, once the drone has finished it, no matter at what altitude the mission was being performed, I want the drone to perform a return home.

The return home works fine but the problem is that the drone always go to 30m to perform the return home instead of keeping the altitude at which it was performing the mission, for example, if the mission finished at 20m altitude, when the return to home action is called it will fly to 30m altitude and then do the return home, a situation that is not logic. 

I want the drone to perform the return home at the same altitude at which it was initially flying. Is that possible?

Best regards,

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/49156'>Zendesk ticket #49156</a>:<br><br>Dear Customer,

Thank you for contacting DJI.
You can set it with method setGoHomeHeightInMeters.
 ![](https://djisdksupport.zendesk.com/attachments/token/2PxfTMnIMz1W4C4LwwKZ8rRm2/?name=inline-1309733869.png)​

Thanks,

Luce Luo
DJI Developer Support<br><a href='https://djisdksupport.zendesk.com/attachments/token/2PxfTMnIMz1W4C4LwwKZ8rRm2' target='zd_attach'>inline-1309733869.png</a>
<br><p><em><small>°°°</small></em></p>

**Comment by kenargo** [comment]
Possible, yes, but NOT using the return to home function.   What I do is to add a new waypoint at the end of the mission ad set its location to the current (takeoff) location of the drone.  You can copy the altitude value of the current last waypoint into the new added one and you will have the functionality you want.

 

From: laboBea ***@***.***> 
Sent: Friday, June 18, 2021 1:58 AM
To: dji-sdk/Mobile-SDK-Android ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dji-sdk/Mobile-SDK-Android] Return to home (#917)

 

Hello,

When performing waypoint missions, once the drone has finished it, no matter at what altitude the mission was being performed, I want the drone to perform a return home.

The return home works fine but the problem is that the drone always go to 30m to perform the return home instead of keeping the altitude at which it was performing the mission, for example, if the mission finished at 20m altitude, when the return to home action is called it will fly to 30m altitude and then do the return home, a situation that is not logic.

I want the drone to perform the return home at the same altitude at which it was initially flying. Is that possible?

Best regards,
