### ISSUE TITLE
Multiple point of interests in one mission

### ISSUE THREAD

**Issue by vdharankar** [dji-sdk/Mobile-SDK-Android#918]
I am trying to setup a mission with multiple point of interests. I can see they only one point of interest is available in one mission. But I have seen apps doing it with DJI drones , it means somewhere the SDK provides a way to do it ? Please guide on this .

**Comment by kenargo** [comment]
Apps doing this are calculating the direction of the interest points and using that value as the aircraft heading for the next point  Since the heading is equally divided as the aircraft moves the interest point is kept in focus. Make sense? 
-------- Original message --------From: "Vish D." ***@***.***> Date: 6/18/21  12:00 PM  (GMT-08:00) To: dji-sdk/Mobile-SDK-Android ***@***.***> Cc: Subscribed ***@***.***> Subject: [dji-sdk/Mobile-SDK-Android] Multiple point of interests in one mission (#918) 
I am trying to setup a mission with multiple point of interests. I can see they only one point of interest is available in one mission. But I have seen apps doing it with DJI drones , it means somewhere the SDK provides a way to do it ? Please guide on this .

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/49169'>Zendesk ticket #49169</a>:<br><br>Dear Client
Thank you for contacting DJI.

Point of Interst can be only set 1 point. The aircraft heading will always point to the coordinate of point of interest.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by Michael-DJI** [comment]
@kenargo has give the correct answer.
