### ISSUE TITLE
Rotation M300 RTK with WaypointV2 missions

### ISSUE THREAD

**Issue by jimmyfraiture** [dji-sdk/Mobile-SDK-Android#921]
Hello,
I found an inconsistency in the WaypointV2 missions for the Matrice 300 RTK.
When I rotate the gimbal of the M300 directly in the code (with an H20 or a P1) the ABSOLUTE_ANGLE are related to the drone's heading. But when the same Rotation is used by a WaypointV2, ABSOLUTE_ANGLE are related to the true North.

I think both have to unified in one single behaviour

**Comment by dji-dev** [comment]
Agent comment from William Wong in <a href='https://djisdksupport.zendesk.com/agent/tickets/49225'>Zendesk ticket #49225</a>:<br><br>Dear Client
Thank you for contacting DJI.

I think this is a bug. We will raise a ticket internally and check.

Hopefully our solution can help you.
Kindly Regards,
DJI Developer Support
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
This is the design. Because in waypointMission, the aircraft heading is changing frequently, and the reference geo model is the ground coordinate system, so the absolute degrees in waypointMission is according the the ground coordinate system which is according to true North. We will add this information on the documentation later on.
