### ISSUE TITLE
4.0 SDK Documentation Question

### ISSUE THREAD

**Issue by jtuchek** [dji-sdk/Mobile-SDK-Android#94]
For `DJIWaypointOperator` there doesn't seem to be any documentation about limiting certain functionality such as `FlightPathMode` and `finishedAction`

These used to be limited to only the Inspire 1 and the Phantom 3 series according to 3.5.X documentation.

With the new 4.0 release, are those functions now available for all devices?

**Comment by jtuchek** [comment]
Same question for `HeadingMode`, `PointOfInterest`, and `PointOfInterestMode`

this would be a huge improvement 👍

**Comment by kenargo** [comment]
I’m sure they are not because these are per-firmware but DJI can confirm.

 

Personally, what I would like to see (somewhat related to your question) are functions to query what operations are available (similar to camera capabilities).  I really don’t like needing to add conditional code with listings of UAV models when the SDK knows this information.

 

The real value in the SDK is to make it easy to write for multiple drones and the SDK comes close but as long as developers need to have code that looks at the UAV model the SDK comes up short on helping the developers be most efficient.

**Comment by jtuchek** [comment]
Being a firmware constraint makes sense - although during some testing I was able to get the `flightPathMode` to work with the Phantom 4 Pro.

Overall wondering if those limitations are not just artifacts from old limitations. Maybe newer versions of firmware of the Phantom 4, Phantom 4 Pro, Inspire 1 Pro, Inspire 2 actually have support.

We'll be test flying to make sure over the next few days with all of our test devices.

**Comment by jtuchek** [comment]
@kenargo ^^

**Comment by oliverou** [comment]
Hi @jtuchek , @kenargo , all the DJIWaypointMissionOperator functionalities are supported by all the drone devices, like Phantom 3 Series, Phantom 4 Series, Inspire series, etc. But excepts for Osmo series.
