### ISSUE TITLE
DJI SDK 4.15 Enterprise Advanced Cannot Switch Lenses

### ISSUE THREAD

**Issue by MichHighlander** [dji-sdk/Mobile-SDK-Android#956]
Hello,
I am trying to switch my Mavic 2 Enterprise Advanced from Thermal to Zoom.
Here is my code:
 
camera.setCameraVideoStreamSource(CameraVideoStreamSource.INFRARED_THERMAL, new CommonCallbacks.CompletionCallback() {
                        @Override
                        public void onResult(DJIError djiError) {
                            if (djiError != null) Log.d(TAG, "Change thermal err: " + djiError.getDescription());
                        }
                    });
The operation is not complete and the error msg i get is: "The feature is unsupported"

**Comment by DJI-William** [comment]
You need to use lens(1).setDisplayMode to switch between Thermal/Visual/MSX/PIP mode.

**Comment by mayurpatil307** [comment]
@DJI-William I have 2 queries over this:

- By lens(1).setDisplayMode, do you mean:

cameraInst.getLens(1).setDisplayMode(SettingsDefinitions.DisplayMode.THERMAL_ONLY, djiError1 
OR
int lensIndex = CommonUtil.getLensIndex(0, SettingsDefinitions.LensType.WIDE);
cameraInst.getLens(lensIndex).setDisplayMode(SettingsDefinitions.DisplayMode.THERMAL_ONLY, djiError1 -> {


- Should we use camera or cameraIR ??
camera = getProductInstance().getCameraWithComponentIndex( x );  --> what should be the value of 'x' in order to implement Thermal in M2EA.

**Comment by DJI-William** [comment]
You should use cameraInst.getLenses to get a a list of lens for M2EA. I think the index 1 of this list points to the Infrared lens. Once you get this lens object. You can call lens.setDisplayMode(). Mavic 2 Enterprise Advanced should only have 1 camera with 2 lenses. the value of X should be 0 I think.
