### ISSUE TITLE
Real time waypoint editing

### ISSUE THREAD

**Issue by zijian98** [dji-sdk/Mobile-SDK-Android#972]
Hi, may I know if there's a way to edit a waypoint (altitude, coordinates) in real time during a mission flight and allows the drone to update and proceed to the newly set waypoint?

Thanks

**Comment by kenargo** [comment]
There is not. Since a mission is intended as a start and forget there is no live runtime update to the mission. 
-------- Original message --------From: zijian98 ***@***.***> Date: 7/18/21  9:29 PM  (GMT-08:00) To: dji-sdk/Mobile-SDK-Android ***@***.***> Cc: Subscribed ***@***.***> Subject: [dji-sdk/Mobile-SDK-Android] Real time waypoint editing (#972) 
Hi, may I know if there's a way to edit a waypoint (altitude, coordinates) in real time during a mission flight and allows the drone to update and proceed to the newly set waypoint?
Thanks

**Comment by zijian98** [comment]
Alright thx!
