### ISSUE TITLE
为什么注册SDK后一直在采集定位

### ISSUE THREAD

**Issue by luoyexk** [dji-sdk/Mobile-SDK-Android#989]
调用`DJISDKManager.getInstance().registerApp(context, listener)`后, 可以在状态栏看到定位图标, 

不论App处于前台后台, 定位功能从未停止, 即使没有连接无人机也会采集定位

# 如何关闭定位

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51065'>Zendesk ticket #51065</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
需要与工程师确认下，您使用的是哪个SDK版本？

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by luoyexk** [comment]
djiSdkVersion = "4.15"
        djiUXSDKVersion = "4.14"
        djiUXBeta = 'v0.5.1'

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51065'>Zendesk ticket #51065</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
好的。
确认需要一定时间，一旦有任何进展我们将会再次联系您。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51065'>Zendesk ticket #51065</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
您可以参考下如下工程师回复：
飞控类，飞行安全类都会调用手机的定位系统。想关闭定位，可以用下面两个方法。

- 从手机端关闭定位功能。
- Manifest里去除ACCESS-FINE_LOCATION，LOCATION_SERVICE，GPS_PROVIDER等权限。
另外想了解下为什么在意定位的问题？

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51065'>Zendesk ticket #51065</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by luoyexk** [comment]
上述提及的两个方法虽然能关闭, 但不可避免的影响到其他应用和我们应用定位功能的使用.

因为我们把`DJISDKManager.getInstance().registerApp(context, listener)`放在了首页, 但真正使用无人机却在比较深的界面, 所以一打开App就看到定位icon的出现感觉很奇怪.

之所以在首页调用registerApp, 是为了能在短时间连接上无人机, 不需要等待漫长的注册回调结果.

理想的情况是app处于后台, 定位自动关闭, 处于前台酌情开启定位

**Comment by dji-dev** [comment]
Agent comment from Luce Luo in <a href='https://djisdksupport.zendesk.com/agent/tickets/51065'>Zendesk ticket #51065</a>:<br><br>尊敬的用户，

 您好！感谢您联系DJI 大疆创新。
十分抱歉，只要同意了权限，SDK内部会相对应跑起来，比较难实现您的案例情景。
开启定位也是为更安全的使用飞机，如辅助返航，禁飞等逻辑。

非常感谢您的理解与配合，祝您生活愉快！

Best Regards,

DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
