### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by zijian98** [dji-sdk/Mobile-SDK-Android#994]
I am building the playback media feature in my app. However, whenever I tried to implement the UX SDK, I got this error on Android Studio

`Could not HEAD 'https://mapbox.bintray.com/mapbox/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom'. Received status code 403 from server: Forbidden`

How to fix this? 
Thanks

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51320'>Zendesk ticket #51320</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by DJI-William** [comment]
Try implement the jcenter in build.gradle repositories section.

repositories {
    mavenLocal()
    jcenter()
}
