### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by panzf** [dji-sdk/Mobile-SDK-Android#995]
dji-uxsdk:4.14：PreFlightCheckListPanel 导致控件内存泄漏（重复连接遥控器）

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51336'>Zendesk ticket #51336</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by luoyexk** [comment]
可以试下UX SDK BETA 的控件, 

地址: https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android


### 顶部状态栏
```
        <dji.ux.beta.core.widget.systemstatus.SystemStatusWidget
            android:id="@+id/system_status_widget"
            android:layout_width="@dimen/dp_238"
            android:layout_height="@dimen/dp_25" />
```

### 代替PreFlightCheckListPanel 状态详情面板
```
    <dji.ux.beta.core.panel.systemstatus.SystemStatusListPanelWidget
        android:id="@+id/widget_panel_system_status_list"
        android:layout_width="0dp"
        android:layout_height="0dp"
        android:background="@color/uxsdk_black_70_percent"
        android:divider="@color/uxsdk_light_gray_900"
        android:dividerHeight="0.5dp"
        android:paddingStart="@dimen/uxsdk_spacing_normal"
        android:paddingLeft="@dimen/uxsdk_spacing_normal"
        android:paddingEnd="@dimen/uxsdk_spacing_normal"
        android:paddingRight="@dimen/uxsdk_spacing_normal"
        android:visibility="gone"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintWidth_percent="0.95"
        app:uxsdk_excludeItem="unit_mode|novice_mode|rc_stick_mode"
        app:uxsdk_titleBarBackgroundColor="@color/uxsdk_black" />
```

**Comment by DJI-William** [comment]
先使用楼上提示的UXSDK BETA版本吧，UXSDK4.14的泄漏问题我们已经提单给研发排期去解决。
