### ISSUE TITLE
指点飞行是否使用经纬度坐标

### ISSUE THREAD

**Issue by Swordce** [dji-sdk/Mobile-SDK-Android#996]

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51362'>Zendesk ticket #51362</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by dji-dev** [comment]
Agent comment from sean.zhou in <a href='https://djisdksupport.zendesk.com/agent/tickets/51362'>Zendesk ticket #51362</a>:<br><br>尊敬的开发者，
您好，感谢您联系DJI 大疆创新。

指点飞行的目标点传入的参数是图像点。图像点范围为[0,1]，其中(0,0)为左上角，(1,1)为右下角。

希望我们的解决方案能够帮到您，感谢您的邮件，祝您生活愉快！

Best Regards,
DJI 大疆创新SDK技术支持
<br><p><em><small>°°°</small></em></p>
