### ISSUE TITLE
 M2EA use MSDK 4.15 can not get ThermalAreaTemperatureAggregations

### ISSUE THREAD

**Issue by bortenchung** [dji-sdk/Mobile-SDK-Android#997]
Aircraft : DJI Mavic 2 Enterprise Advanced
DisplayMode: THERMAL_ONLY
SDK :  DJI Android Mobile SDK 4.15
code ：
![image](https://user-images.githubusercontent.com/79894923/128451811-ef5e1e68-c6fa-4050-afbf-4ea93f1b84c7.png)
logcat output:
![image](https://user-images.githubusercontent.com/79894923/128451990-223bb8d1-5c3c-4127-a759-5364c73fbc8f.png)
found no callback  in 60 seconds

So, how to get the ThermalAreaTemperatureAggregations of M2EA?

**Comment by dji-dev** [comment]
Agent comment from DJI SDK in <a href='https://djisdksupport.zendesk.com/agent/tickets/51374'>Zendesk ticket #51374</a>:<br><br>尊敬的开发者，感谢您联系DJI 大疆创新
由于github不是我们主要的咨询渠道，您的问题可能跟进不及时。我们建议您通过填写表单（ https://djisdksupport.zendesk.com/hc/zh-cn/requests/new ）向我们反馈问题。或者您也可以在论坛发帖，与其它开发者交流。论坛链接：https://djisdksupport.zendesk.com/hc/zh-cn/community/topics

Dear developer, thank you for contacting DJI.
Since github is not our main consultation channel, your questions may not be followed up in time. We recommend that you fill in the form (https://djisdksupport.zendesk.com/hc/en-us/requests/new) to report problems to us. Or you can post in the forum to communicate with other developers. Forum link: https://djisdksupport.zendesk.com/hc/zh-cn/community/topics
<br><p><em><small>°°°</small></em></p>

**Comment by bortenchung** [comment]
Solved。Should do this to use the AREA_METERING function.
lens.setThermalMeasurementMode(ThermalMeasurementMode.AREA_METERING,callback).
